server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true    
          
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

          discovery:
            locator:
              enabled: true
          routes:
            - id: micro-user
              uri: lb://micro-user
              predicates:
                - Path=/api/v0/users/**
            - id: micro-packagefilter
              uri: lb://micro-packagefilter
              predicates:
                - Path=/api/v0/packages/destination,/api/v0/packages/status,/api/v0/packages/maxPrice,/api/v0/packages/filter
            - id: micro-package
              uri: lb://micro-package
              predicates:
                - Path=/api/v0/packages/**   
            - id: micro-reservation
              uri: lb://micro-reservation
              predicates:
                - Path=/api/v0/reservations/**
            - id: micro-payment
              uri: lb://micro-payment
              predicates:
                - Path=/api/v0/payments/**  
            - id: micro-reservationtracking
              uri: lb://micro-reservationtracking
              predicates:
                - Path=/api/v0/reservationtracking/** 
            - id: micro-reports
              uri: lb://micro-reports
              predicates:
                - Path=/api/v0/reports/**  
            - id: micro-reservation-discounts
              uri: lb://micro-reservation
              predicates:
                - Path=/api/v0/discounts/**                             